// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package nbaData

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NbaPlayerSalary struct {
	ID         int64		`json:"id"`
	Name       string 		`json:"name"`
	Salary2025 pgtype.Text	`json:"salary2025"`
	Salary2026 pgtype.Text	`json:"salary2026"`
	Salary2027 pgtype.Text	`json:"salary2027"`
	Salary2028 pgtype.Text	`json:"salary2028"`
	Salary2029 pgtype.Text	`json:"salary2029"`
}

type NbaTeamSalary struct {
	ID         int64 		`json:"id"`
	Name       string 		`json:"name"`
	Salary2025 pgtype.Text 	`json:"salary2025"`
	Salary2026 pgtype.Text 	`json:"salary2026"`
	Salary2027 pgtype.Text 	`json:"salary2027"`
	Salary2028 pgtype.Text 	`json:"salary2028"`
	Salary2029 pgtype.Text 	`json:"salary2029"`
}
