// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package nbaData

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NbaPlayerSalary struct {
	ID         int64
	Name       string
	Salary2025 pgtype.Text
	Salary2026 pgtype.Text
	Salary2027 pgtype.Text
	Salary2028 pgtype.Text
	Salary2029 pgtype.Text
}

type NbaTeamSalary struct {
	ID         int64
	Name       string
	Salary2025 pgtype.Text
	Salary2026 pgtype.Text
	Salary2027 pgtype.Text
	Salary2028 pgtype.Text
	Salary2029 pgtype.Text
}
